# Generated by cucumber-sinatra. (2015-02-01 20:09:44 +0000)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/rock_paper_scissors.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = rock_paper_scissors

class rock_paper_scissorsWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  rock_paper_scissorsWorld.new
end
